language: bash
addons:
  apt:
    packages:
      - python3-pip
      - jq
before_install:
  - pwd
  - pip3 install --user youtube-dl
  - mkdir ~/src
  - git clone https://github.com/progrhyme/shove.git
  - ./shove/bin/shove -V
  - git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  - yes | ~/.fzf/install
  - . ~/.bashrc
  - wget https://github.com/peco/peco/releases/download/v0.5.3/peco_linux_amd64.tar.gz
  - tar xvf ./peco_linux_amd64.tar.gz
  - cp ./peco_linux_amd64/peco ~/.local/bin
env:
  global:
    - YOV_VLC_OPTIONS=""
    - PATH=$PATH:$HOME/.local/bin
script:
  - ./shove/bin/shove test.t -v
