language: bash
addons:
  apt:
    packages:
      - python3-pip
      - jq
      - peco
before_install:
  - pwd
  - pip3 install --user youtube-dl
  - mkdir ~/src
  - git clone https://github.com/progrhyme/shove.git
  - ./shove/bin/shove -V
  - git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  - yes | ~/.fzf/install
  - . ~/.bashrc
env:
  global:
    - YOV_VLC_OPTIONS=""
script:
  - ./shove/bin/shove test.t -v
