language: bash
addons:
  apt:
    packages:
      - python3-pip
      - jq
before_install:
  - pwd
  - pip3 install --user youtube-dl
  - mkdir ~/src
  - git clone https://github.com/progrhyme/shove.git ~/src/shove
  - alias shove="$HOME/src/shove/bin/shove"
  - shove -V
env:
  global:
    - YOV_VLC_OPTIONS=""
install:
  - ./yov.sh init
script:
  - shove test.t
